# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f06188c25e2f8cae1f50e5667c22eef9c3fcb26392445dcff828c38e1ca77999bafb28e82e47541db9d9c2cfc463b2f776b9a8087e2083c4a6503b6a0adf1db4

test:
  secret_key_base: d742b143c49a1e26efc9b9c35e4ec4cfe443a70bd9fc46da1fd575eb345c830611560c5fba5a8678cf2daf09cc5a60fa01dd413742ea609dcc38a47ba90cecc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
